klaviaturregistret/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'klaviaturregistret.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'', include('web.urls')),
)

web/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView, DetailView, ListView, FormView, CreateView, UpdateView, DeleteView
from django.contrib.auth.views import logout
from django.contrib.auth.decorators import login_required
from web.models import Venue
from web.views import LandingPage, AdvancedSearchView, VenueList, VenueDetail, CreateVenue, DeleteVenue, CreateDescription, CreateContact, CreateImage

urlpatterns = patterns('',
    url(r'^$', VenueList.as_view(), name='venue_list'),
    url(r'^venue/(?P<pk>\d+)/$', VenueDetail.as_view(), name='venue_detail'),
    url(r'^venue/(?P<pk>\d+)/delete$', login_required(DeleteVenue.as_view()), name='delete_venue'),
    url(r'^venue/(?P<pk>\d+)/create_description$', login_required(CreateDescription.as_view()), name='create_description'),
    url(r'^venue/(?P<pk>\d+)/create_contact$', login_required(CreateContact.as_view()), name='create_contact'),
    url(r'^venue/(?P<pk>\d+)/create_image$', login_required(CreateImage.as_view()), name='create_image'),
    url(r'^create_venue$', login_required(CreateVenue.as_view()), name='create_venue'),
    url(r'^search$', AdvancedSearchView.as_view(), name='search'),

    url(r'^accounts/login', LandingPage.as_view(), name='landingpage'),
    url(r'accounts/profile', login_required(TemplateView.as_view(template_name="profile.html")), name='profile'),
    url(r'accounts/logout', logout, {'next_page': '/'}, name='logout'),
)

web/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.core.files import File
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.core.urlresolvers import reverse

from PIL import Image as PILImage
import os
import StringIO

# Create your models here.
class Venue(models.Model):
    name = models.CharField(max_length=128, verbose_name='Namn')
    audience_min = models.IntegerField(blank=True)
    audience_max = models.IntegerField(blank=True)

    def get_absolute_url(self):
        return reverse('venue_detail', kwargs={'pk': self.pk})

    def __unicode__(self):
        return self.name

class Description(models.Model):
    author = models.ForeignKey(User, verbose_name="Användare")
    text = models.TextField(max_length=8192, verbose_name="Beskrivning")
    timestamp = models.DateTimeField(auto_now_add=True)
    venue = models.ForeignKey(Venue, related_name="descriptions")

    class Meta:
        ordering = ['-timestamp']

    def __unicode__(self):
        # Return the first five words.
        return ' '.join(self.text.split()[:5])

class Address(models.Model):
    author = models.ForeignKey(User, verbose_name="Användare")
    text = models.TextField(max_length=512, verbose_name="Adress")
    venue = models.OneToOneField(Venue, blank=True, related_name="address")

    def __unicode__(self):
        return '{venue}, {address}'.format(venue=self.venue.name, address=self.text)

class Contact(models.Model):
    name = models.CharField(max_length=128, blank=True, verbose_name="Namn")
    email = models.EmailField(blank=True)
    phone = models.CharField(max_length=128, blank=True, null=True, verbose_name="Telefon")
    timestamp = models.DateTimeField(auto_now_add=True)
    added_by = models.ForeignKey(User)
    venue = models.ForeignKey(Venue, related_name="contacts")

    def __unicode__(self):
        return self.name

class Image(models.Model):
    caption = models.CharField(max_length=128, null=True, blank=True)
    image = models.ImageField(upload_to='images', null=True, blank=True)
    thumbnail = models.ImageField(upload_to='thumbnails', blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    added_by = models.ForeignKey(User)
    venue = models.ForeignKey(Venue, related_name="images")

    def make_thumbnail(self):
        image = PILImage.open(self.image.path)
        image.thumbnail((200,200))
        thumb_io = StringIO.StringIO()
        image.save(thumb_io, format='JPEG')

        image_basename, image_extension = os.path.splitext(os.path.basename(self.image.path))
        thumbnail_filename = "{basename}_tn{extension}".format(basename=image_basename, extension=image_extension)

        thumb_file = InMemoryUploadedFile(thumb_io, None, thumbnail_filename, 'image/jpeg', thumb_io.len, None)

        self.thumbnail.save(thumbnail_filename, thumb_file, save=True)

    def __unicode__(self):
        if self.caption:
            return self.caption
        else:
            return "Image {pk}".format(self.pk)

web/templates/base.html
{% load staticfiles %}
{% load i18n %}
{% load bootstrap3 %}
<!DOCTYPE html>
<html class="no-js" lang="">
  <head>
    {% block head %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block "title" %}{% endblock %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'web/font/MyFontsWebfontsKit.css' %}">
    {% bootstrap_css %}
    <link href="{% static 'web/css/docs.css' %}" media="screen" rel="stylesheet">
    <link href="{% static 'web/css/klaviaturregistret.css' %}" media="screen" rel="stylesheet">
    {% endblock %}
  </head>
  <body>
    {% block body %}
    <a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>
    <!-- Navstrip -->
    {% block "header" %}
    <header class="navbar navbar-static-top bs-docs-nav" id="top" role="banner">
      <div class="container">
        <div class="navbar-header">
          <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a href="{% url 'venue_list' %}" class="navbar-brand">Klaviaturregistret</a>
        </div>
        <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
          <ul class="nav navbar-nav">
            <li>
              <a href="{% url 'venue_list' %}">Lokaler</a>
            </li>
            <li>
              <a href="{% url 'search' %}">Sök</a>
            </li>
            <li>
              <a href="#">Om</a>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li class="navbar-link">
              <a href="{% url 'profile' %}">{{ user.get_full_name }}</a>
            </li>
            <li>
              <a class="small" href="{% url "logout" %}">Logga ut</a>
            </li> 
            {% else %}
            <li class="navbar-text">
              Logga in med
            </li>
            <li class="navbar-link">
              <a href="{% url "social:begin" "facebook" %}">Facebook</a>
            </li>
            <li class="navbar-link">
              <a href="{% url "social:begin" "google-oauth2" %}">Google</a>
            </li>
            {% endif %}
          </ul>
        </nav>
      </div>
    </header>
    {% endblock %}
    {% block "content" %}
    <div class="bs-docs-header" id="content">
      <div class="container">
        <h1>Innehåll goes here</h1>
        <p>Mer innehåll här.</p>
      </div>
    </div>
    <div class="container bs-docs-container">
      <div class="row">
        <div class="col-md-9" role="main">
          <h1 id="error" class="page-header">Rubb rubb</h1>
          <p class="lead">Den här texten ska aldrig dyka upp på sajten.</p>
          <p>Se till att sidmallarna innehåller ett content-block.</p>
        </div>
      </div>
    </div> 
    {% endblock %}
    <!-- Footer ================================================== -->
    {% block "footer" %}
    <footer class="bs-docs-footer" role="contentinfo">
      <div class="container">
        <img class="logo" src="{% static 'web/images/markovlaboratorierna.svg' %}" alt="Markovlaboratorierna" width="120px">
        <p class="lead">Hopsnickrad i Markovlaboratorierna hösten 2014.</p>
        <p class="text-muted">Källkoden för sajten, som är skriven i <a href="https://djangoproject.com">Django</a>, finns tillgänglig <a href="https://github.com/eriklavander/klaviaturregistret">här</a>.</p>
        <p class="text-muted">Sajtens utseende baseras på <a href="https://getbootstrap.com/">Bootstrap</a>, typsnittet <a href="http://fonts.kylewaynebenson.com/tide-sans/">Tide Sans</a>, diverse fotomaterial från olika källor på <a href="https://flickr.com">Flickr</a> och, naturligtvis, bilder och text från sajtens användare.
      </div>
    </footer>
    {% endblock %}
    {% block "javascript" %}
      <script src="{% bootstrap_jquery_url %}"></script>
      {% bootstrap_javascript %}
    {% endblock %}
    {% endblock %}
  </body>
</html>

web/templates/create_contact.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block "title"%}Lägg till kontaktuppgifter - Klaviaturregistret{% endblock %}
{% block "content" %}
<div class="bs-docs-header" id="content">
  <div class="container">
    <h2>Lägg till kontaktuppgifter</h2>
  </div>
</div>
<div class="container bs-docs-container">
  <form action="{% url 'create_description' pk=1 %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    {% buttons %}
    <button type="submit" class="btn btn-primary">
      {% bootstrap_icon "star" %} Lägg till kontaktuppgift
    </button>
    {% endbuttons %}
  </form>
</div>
{% endblock %}

web/templates/create_description.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block "title"%}Redigera beskrivning - Klaviaturregistret{% endblock %}
{% block "content" %}
<div class="bs-docs-header" id="content">
  <div class="container">
    <h2>Redigera beskrivning</h2>
  </div>
</div>
<div class="container bs-docs-container">
  <form action="{% url 'create_description' pk=1 %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    {% buttons %}
    <button type="submit" class="btn btn-primary">
      {% bootstrap_icon "star" %} Lägg till ny beskrivning
    </button>
    {% endbuttons %}
  </form>
</div>
{% endblock %}

web/templates/create_image.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block "title"%}Lägg till bild - Klaviaturregistret{% endblock %}
{% block "content" %}
<div class="bs-docs-header" id="content">
  <div class="container">
    <h2>Lägg till bild</h2>
  </div>
</div>
<div class="container bs-docs-container">
  <form action="{% url 'create_image' pk=1 %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}
        <div class="fieldWrapper">
            {{ field.errors }}
            {{ field.label_tag }} {{ field }}
        </div>
    {% endfor %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">
      {% bootstrap_icon "star" %} Lägg till bild
    </button>
    {% endbuttons %}
  </form>
</div>
{% endblock %}

web/templates/home.html
{% extends "base.html" %}
{% block content %}
<div class="bs-docs-header" id="content">
  <div class="container">
    <h1>Klaviaturregistret</h1>
    <p>Global CSS settings, fundamental HTML elements styled and enhanced with extensible classes, and an advanced grid system.</p>
    <div id="carbonads-container"><div class="carbonad"><div id="azcarbon"></div><script>var z = document.createElement("script"); z.async = true; z.src = "http://engine.carbonads.com/z/32341/azcarbon_2_1_0_HORIZ"; var s = document.getElementsByTagName("script")[0]; s.parentNode.insertBefore(z, s);</script></div></div>

  </div>
</div>
<p>Bar</p>
{% endblock %}

web/templates/landingpage.html
{% extends "base.html" %}
{% block "title"%}Klaviaturregistret{% endblock %}
{% block "content" %}
<div>
  <div class="container landing-bg">
    <div class="landing-form">
      <a href="{% url "social:begin" "facebook" %}" class="btn btn-lg btn-primary btn-block">Logga in med Facebook</a>
      <a href="{% url "social:begin" "google-oauth2" %}" class="btn btn-lg btn-primary btn-block">Logga in med Google</a>
    </div>
  </div>
  <p>Bild av Gianpero Addis (<a href="https://www.flickr.com/photos/punkjazz/">Flickr</a>), CC-BY 2.0</p>
</div>
{% endblock %}

web/templates/profile.html
{% extends "base.html" %}
{% block "title"%}{{ user.get_full_name }} - Klaviaturregistret{% endblock %}
{% block "content" %}
<div class="bs-docs-header" id="content">
  <div class="container">
    <h2>{{ user.get_full_name }}</h2>
  </div>
</div>
<div class="container bs-docs-container">
  <div class="row">
    <h3>Beskrivningar</h3>
    {% for description in user.description_set.all %}
    <h4><a href="{% url 'venue_detail' pk=description.venue_set.get.pk %}">{{ description.venue_set.get.name }}</a></h4>
    <p>{{ description.text }}</p>
    <footer class="text-muted">{{ description.timestamp }}</footer>
    {% empty %}
    <p class="text-muted">Inga beskrivningar</p>
    {% endfor %}
    <h3>Bilder</h3>
    {% for image in user.image_set.all %}
    <div class="col-md-2">
      <a href="{{ image.image.url }}"><img src="{{ image.thumbnail.url }}" alt="{{ image.caption }}" class="img-responsive img-rounded" /></a>
      {% if image.venue_set.get %}
      <p><a href="{% url 'venue_detail' image.venue_set.get.id %}">{{ image.venue_set.get.name }}</a></p>
      {% endif %}
      <p class="text-muted">{{ image.timestamp }}</p>
    </div>
    {% empty %}
    <p class="text-muted">Inga bilder</p>
    {% endfor %}
  </div>
</div>
{% endblock %}

web/templates/search.html
{% extends "base.html" %}
{% block "title"%}Sök - Klaviaturregistret{% endblock %}
{% block "content" %}
<div class="bs-docs-header" id="content">
  <div class="container">
    <h1>Sök</h1>
  </div>
</div>
<div class="container bs-docs-container">
  <div class="row">
    <form action="{% url 'search' %}" method="get">
      {{ searchform }}
      <input type="submit" value="Sök" />
    </form>
    {% if has_query %}
    <p class="text-muted">{{ hits.count }} träff{{ hits.count|pluralize:"ar" }}.</p>
    {% endif %}
    {% for venue in hits %}
    <div class="media row">
      <a class="media-left" href="{% url 'venue_detail' venue.id %}">
        <img src="{{ venue.images.all.0.thumbnail.url }}" alt="{{ venue.images.all.0.images.caption }}">
      </a>
      <div class="media-body">
        <h4 class="media-heading"><a href="{% url 'venue_detail' venue.id %}">{{ venue.name }}</a></h4>
        <div class="col-md-6">
          <p class="small">{{ venue.descriptions.all.0.text | truncatewords:40 }}</p>
          <p class="text-muted small">&mdash; {{ venue.descriptions.all.0.author }}, {{ venue.descriptions.all.0.timestamp }}</p>
        </div>
        <p class="small">Adress: {{ venue.address }}</p>
        <p class="small">Publik: {{ venue.audience_min }} &mdash; {{ venue.audience_max }}</p>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

web/templates/venue_detail.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block "title"%}{{ object.name }} - Klaviaturregistret{% endblock %}
{% block "content" %}
<div class="bs-docs-header" id="content">
  <div class="container">
    <h1>{{ object.name }}</h1>
    <p>{{ object.address.text }}</p>
    <p>Publik: {{ object.audience_min }} - {{ object.audience_max }}
  </div>
</div>

<div class="container bs-docs-container">
  <div class="row">
    {% for image in object.images.all %}
    <div class="col-md-1 col-xs-3">
      <a href="{{ image.image.url }}">
        <img title="{{ image.caption }}" src="{{ image.thumbnail.url }}" alt="{{ image.caption }}" class="img-responsive img-rounded" />
        <div class="caption">
          <p class="text-muted small">{{ image.caption | truncatewords:10 }}</p>
        </div>
      </a>
    </div>
    {% empty %}
    <p class="text-muted">Inga bilder än!</p>
    {% endfor %}
  </div>
  {% if user.is_authenticated %}
  <div class="row">
    <div class="col-md-6">
      <a data-toggle="collapse" data-target="#image-form" aria-expanded="true" aria-controls="demo">
        Lägg till bild<span class="caret"></span>
      </a>
      <div id="image-form" class="collapse">
        <form action="{% url 'create_image' pk=object.pk %}" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {# bootstrap_form image_form #}
          {{ image_form }}
          {% buttons %}
          <button type="submit" class="btn btn-primary">
              {% bootstrap_icon "picture" %} Lägg till bild
          </button>
          {% endbuttons %}
        </form>
      </div>
    </div>
  </div>
  {% endif %}
  <div class="row">
    <div class="col-md-6">
      <h2>Beskrivning</h2>
      {% if object.descriptions.all.0 %}
      <p>{{ object.descriptions.all.0.text }}</p>
      <p class="text-muted">&mdash; {{ object.descriptions.all.0.author }}, {{ object.descriptions.all.0.timestamp }}</p>
      {% else %}
      <p class="text-muted">Inga beskrivningar än.</p>
      {% endif %}

      {% if object.descriptions.all.1 %}
      <div>
        <a class="" data-toggle="collapse" data-target="#old_descriptions" aria-expanded="true" aria-controls="demo">
          Visa äldre beskrivningar<span class="caret"></span>
        </a>
        <div id="old_descriptions" class="collapse">
          {% for description in object.descriptions.all|slice:"1:" %}
          <p>{{ description.text | linebreaks }}</p>
          <p class="text-muted">&mdash; {{ description.author }}, {{ description.timestamp }}</p>
          {% endfor %}
        </div>
      </div>
      {% endif %}
      {% if user.is_authenticated %}
      <div>
        <a class="" data-toggle="collapse" data-target="#description-form" aria-expanded="true" aria-controls="demo">
          Redigera beskrivning<span class="caret"></span>
        </a>
        <div id="description-form" class="collapse">
          <form action="{% url 'create_description' pk=object.pk %}" method="post">
            {% csrf_token %}
            {% bootstrap_form description_form %}
            {% buttons %}
            <button type="submit" class="btn btn-primary">
                {% bootstrap_icon "star" %} Redigera beskrivning
            </button>
            {% endbuttons %}
          </form>
        </div>
      </div>
      {% endif %}
    </div>

    <div class="col-md-4 pull-right" role="map">
      <h2>Karta</h2>
      <iframe width="400" height="400" frameborder="0" style="border:0"
        src="https://www.google.com/maps/embed/v1/place?key=AIzaSyBq7cIi8M4OreHflOzG328po6aiTCNtv2A
          &q={{ object.address }}">
      </iframe>
    </div>

    <div class="col-md-6"> 
      <h2>Kontaktuppgifter</h2>
      {% for contact in object.contacts.all %}
      <p>
        <strong>{{ contact.name }}</strong><br/>
        <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> <a href="mailto:{{ contact.email }}">{{ contact.email|default_if_none:"-" }}</a><br/>
        <span class="glyphicon glyphicon-earphone" aria-hidden="true"></span> {{ contact.phone|default_if_none:"-" }}<br/>
      </p>
      {% empty %}
      <p class="text-muted">Kontaktuppgifter saknas.</p>
      {% endfor %}
      {% if user.is_authenticated %}
      <div>
        <a class="" data-toggle="collapse" data-target="#contact-form" aria-expanded="true" aria-controls="demo">
          Lägg till kontaktuppgift<span class="caret"></span>
        </a>
        <div id="contact-form" class="collapse">
          <form action="{% url 'create_contact' pk=object.pk %}" method="post">
            {% csrf_token %}
            {% bootstrap_form contact_form %}
            {% buttons %}
            <button type="submit" class="btn btn-primary">
                {% bootstrap_icon "star" %} Lägg till kontaktuppgift
            </button>
            {% endbuttons %}
          </form>
        </div>
      </div>
      {% endif %}
    </div>
  </div>
  {% if user.is_authenticated %}
  <div class="row">
    <div class="col-md-6">
      <form action="{% url 'delete_venue' pk=object.pk %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">
          {% bootstrap_icon "trash" %} Radera lokal
        </button>
      </form>
    </div>
  </div>
  {% endif %}
</div>
{% endblock %}

web/templates/venue_form.html
{% extends "base.html" %}
{% block "title"%}{{ object.name }} - Klaviaturregistret{% endblock %}
{% block "content" %}
<div class="bs-docs-header" id="content">
  <div class="container">
    <h1>Skapa ny lokal</h1>
  </div>
</div>

<div class="container bs-docs-container">
  <div class="row">
    <form action="" method="post">{% csrf_token %}
      {{ form.as_table }}
      <input type="submit" value="Create" />
    </form>
  </div>
</div>
{% endblock %}

web/templates/venue_list.html
{% extends "base.html" %}
{% load i18n %}
{% load bootstrap3 %}
{% block "title"%}Lokaler - Klaviaturregistret{% endblock %}
{% block "content" %}
<div class="bs-docs-header" id="content">
  <div class="container">
    <h1>Lokaler</h1>
  </div>
</div>
<div class="container bs-docs-container">
  {% for venue in object_list %}
  <div class="media row">
    {% if venue.images.all %}
    <a class="media-left" href="{% url 'venue_detail' venue.id %}">
      <img src="{{ venue.images.all.0.thumbnail.url }}" alt="{{ venue.images.all.0.images.caption }}">
    </a>
    {% endif %}
    <div class="media-body">
      <h4 class="media-heading"><a href="{% url 'venue_detail' venue.id %}">{{ venue.name }}</a></h4>
      <div class="col-md-6">
        {% if venue.descriptions.all %}
        <p class="small">{{ venue.descriptions.all.0.text | linebreaks | truncatewords:40 }}</p>
        <p class="text-muted small">&mdash; {{ venue.descriptions.all.0.author }}, {{ venue.descriptions.all.0.timestamp }}</p>
        {% endif %}
      </div>
      <p class="small">Adress: {{ venue.address.text }}</p>
      <p class="small">Publik: {{ venue.audience_min }} &mdash; {{ venue.audience_max }}</p>
    </div>
  </div>
  {% endfor %}
  {% if user.is_authenticated %}
  <div class="row">
    <a class="" data-toggle="collapse" data-target="#create-venue-form" aria-expanded="true" aria-controls="demo">
      Lägg till lokal <span class="caret"></span>
    </a>
    <div id="create-venue-form" class="collapse">
      <form action="{% url 'create_venue' %}" method="post">
        {% csrf_token %}
        {% bootstrap_form create_venue_form %}
        {% buttons %}
        <button type="submit" class="btn btn-primary">
            {% bootstrap_icon "star" %} Lägg till lokal
        </button>
        {% endbuttons %}
      </form>
    </div>
  </div>
  {% endif %}
  {% if is_paginated %}
  <div class="pagination">
    <span class="page-links">
      {% if page_obj.has_previous %}
      <a href="{% url 'venue_list' %}?page={{ page_obj.previous_page_number }}">föregående</a>
      {% endif %}
      <span class="page-current">
          Sida {{ page_obj.number }} av {{ page_obj.paginator.num_pages }}.
      </span>
      {% if page_obj.has_next %}
      <a href="{% url 'venue_list' %}?page={{ page_obj.next_page_number }}">nästa</a>
      {% endif %}
    </span>
  </div>
  {% endif %}
</div>
{% endblock %}